name: triple_example

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter_triple: 1.2.7+4
  get_it: 7.2.0
  equatable: 2.0.5
  flutter_screenutil: 5.5.4
  hive: 2.2.3
  hive_flutter: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  triple_test: 1.0.0+1
  flutter_lints: 2.0.1
  dart_code_metrics: 4.19.1
  build_runner: 2.3.0
  hive_generator: 1.1.3
  mockito: 5.3.2

flutter:
  uses-material-design: true
  generate: true