name: template_bloc
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: 1.0.5
  dio: 4.0.6
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter_screenutil: 5.6.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  get_it: 7.2.0

dev_dependencies:
  bloc_test: 9.1.0
  build_runner: 2.3.0
  change_app_package_name: 1.1.0
  dart_code_metrics: 4.19.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  hive_generator: 1.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - res/assets/
    - res/fonts/

fonts:
  - family: Roboto
    fonts:
      - asset: res/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: res/fonts/Roboto-Thin.ttf
        weight: 200
      - asset: res/fonts/Roboto-Light.ttf
        weight: 300
      - asset: res/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: res/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: res/fonts/Roboto-Semibold.ttf
        weight: 600
      - asset: res/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: res/fonts/Roboto-Black.ttf
        weight: 800
      - asset: res/fonts/Roboto-Black.ttf
        weight: 900
